#! /bin/sh
#
# run script wrapper for tfluna sender
#
# Copyright (c) 2021 ZKM | Hertz-Lab
# Dan Wilcox <dan.wilcox@zkm.de>
#
# BSD Simplified License.
# For information on usage and redistribution, and for a DISCLAIMER OF ALL
# WARRANTIES, see the file, "LICENSE.txt," in this distribution.
#
# This code has been developed at ZKM | Hertz-Lab as part of „The Intelligent
# Museum“ generously funded by the German Federal Cultural Foundation.

DIR="$(dirname $0)"
SCRIPT=tfluna.py

. "$DIR"/venv/bin/activate
"$DIR"/$SCRIPT "$@"
deactivate
